# 主题配置文件
avatar: /img/favicon.png

# 网站ico
favicon: /img/favicon.png

# 网站关键字
keywords: Zebin, Blog, 编程, 生活, 技术

# 主题菜单配置
menu:
  首页: /
  归档: /archives
  分类: /categories
  友链: /links
  兴趣爱好: /hobbies
  关于: /about
  足迹: /map
  Wiki: /wiki
  谢益辉的恶作剧: /smallgame/trick
  设置: /settings

# 为每个菜单项分配一个图标
menu_icons:
  首页: ""
  归档: ""
  分类: ""
  友链: ""
  兴趣爱好: ""
  关于: ""
  足迹: ""
  Wiki: ""
  谢益辉的恶作剧: ""
  设置: ""

# 是否显示文章目录（TOC）
# 即使全局关闭，也可以在单篇文章的 front-matter 中通过 toc: true 单独开启
TOC: true

# 本地搜索
local_search:
  enable: true
  path: search.xml

# RSS 订阅
rss: atom.xml

# 语言切换
i18n:
  enable: true
  default: de  # zh、en 或 de
